# Generated by Django 4.2.7 on 2023-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_review_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='blank.jpeg', null=True, upload_to='book_image'),
        ),
    ]
