# Generated by Django 4.2.7 on 2023-11-23 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
